experiment_params:
  max_epochs: 400
  max_iters: 500
  num_dom: 5000
  num_bou: 1250
  pinn_lr: 0.0001
  nf_lr: 0.0008
  sch_T_0: 500
  sch_T_mult: 1
  pinn_bou_weight: 1
  aas_beta: 10

logging_params:
  Re: 400
  sample_method: "vanilla_pinn"
